# Generated by Django 4.0 on 2022-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregister_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_emp',
            old_name='address',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='model_emp',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='model_emp',
            old_name='age',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='model_emp',
            name='eno',
        ),
        migrations.RemoveField(
            model_name='model_emp',
            name='salary',
        ),
        migrations.AddField(
            model_name='model_emp',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_emp',
            name='password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_emp',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
