# Generated by Django 4.0 on 2022-08-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('departmant', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=20)),
                ('study', models.CharField(max_length=20)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.library')),
            ],
        ),
    ]
