# Generated by Django 4.0 on 2022-08-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_view',
            new_name='Employee',
        ),
    ]
