# Generated by Django 4.0 on 2022-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_reg', '0003_employee_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='address',
            field=models.TextField(max_length=1000),
        ),
    ]
