# Generated by Django 4.0 on 2022-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.IntegerField()),
                ('room_type', models.BooleanField(choices=[('AC', 'AC'), ('Non AC', 'Non AC'), ('King', 'King'), ('Primier', 'Premier')], default='AC')),
                ('images', models.ImageField(upload_to='media')),
            ],
        ),
    ]
