# Generated by Django 4.0 on 2022-07-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
