# Generated by Django 4.0 on 2022-07-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_apply', '0002_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
